- hosts: localhost
  gather_facts: no
  tasks:
  - block:
    - block:
      - block:
        - block:
          - debug: msg="are we there yet?"
        always:
        - debug: msg="a random always block"
      - fail:
      rescue:
      - debug: msg="rescuing from the fail"
